;;;; KLI Dashboard — Activity page CSS

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-activity
  ;; Summary bar
  (".activity-summary" (("display" . "grid")
                        ("grid-template-columns" . "repeat(auto-fit, minmax(100px, 1fr))")
                        ("gap" . "1px")
                        ("background" . "var(--color-border)")
                        ("border" . "1px solid var(--color-border)")
                        ("border-radius" . "2px")
                        ("margin-bottom" . "2rem")
                        ("overflow" . "hidden")))
  (".activity-stat" (("background" . "var(--color-surface)")
                     ("padding" . "1rem")
                     ("text-align" . "center")))
  (".activity-stat .count" (("font-family" . "var(--font-heading)")
                            ("font-size" . "1.4rem")
                            ("color" . "var(--color-heading)")
                            ("line-height" . "1")))
  (".activity-stat .label" (("font-family" . "var(--font-mono)")
                            ("font-size" . "0.6875rem")
                            ("letter-spacing" . "0.12em")
                            ("text-transform" . "uppercase")
                            ("color" . "var(--color-muted)")
                            ("margin-top" . "0.4rem")))
  ;; Filter bar
  (".activity-filters" (("display" . "flex")
                        ("gap" . "0.4rem")
                        ("margin-bottom" . "1.5rem")
                        ("flex-wrap" . "wrap")))
  (".filter-btn" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("letter-spacing" . "0.08em")
                  ("text-transform" . "uppercase")
                  ("padding" . "0.3rem 0.8rem")
                  ("border" . "1px solid var(--color-border)")
                  ("border-radius" . "2px")
                  ("background" . "transparent")
                  ("color" . "var(--color-muted)")
                  ("cursor" . "pointer")
                  ("transition" . "all 0.2s ease")))
  (".filter-btn:hover" (("color" . "var(--color-text)")
                        ("border-color" . "var(--color-accent-dim)")))
  (".filter-btn.active" (("color" . "var(--color-accent)")
                         ("border-color" . "var(--color-accent)")
                         ("background" . "rgba(212, 168, 83, 0.08)")))
  ;; Day group
  (".day-group" (("margin-bottom" . "2rem")))
  (".day-header" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("letter-spacing" . "0.1em")
                  ("text-transform" . "uppercase")
                  ("color" . "var(--color-muted)")
                  ("padding-bottom" . "0.6rem")
                  ("margin-bottom" . "0.75rem")
                  ("border-bottom" . "1px solid var(--color-border)")))
  ;; Event row
  (".event-row" (("display" . "flex")
                 ("align-items" . "flex-start")
                 ("gap" . "0.75rem")
                 ("padding" . "0.5rem 0.75rem")
                 ("border-radius" . "2px")
                 ("transition" . "background 0.15s ease")))
  (".event-row:hover" (("background" . "var(--color-surface)")))
  (".event-icon" (("width" . "20px")
                  ("height" . "20px")
                  ("border-radius" . "2px")
                  ("display" . "flex")
                  ("align-items" . "center")
                  ("justify-content" . "center")
                  ("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("flex-shrink" . "0")
                  ("margin-top" . "1px")))
  (".event-icon.session" (("background" . "rgba(88,166,255,0.12)")
                          ("color" . "#58a6ff")))
  (".event-icon.observation" (("background" . "rgba(74,222,128,0.12)")
                              ("color" . "var(--color-success)")))
  (".event-icon.handoff" (("background" . "rgba(212,168,83,0.12)")
                          ("color" . "var(--color-accent)")))
  (".event-icon.task" (("background" . "rgba(163,113,247,0.12)")
                       ("color" . "#a371f7")))
  (".event-icon.artifact" (("background" . "rgba(248,81,73,0.12)")
                           ("color" . "#f85149")))
  (".event-body" (("flex" . "1")
                  ("min-width" . "0")))
  (".event-title" (("font-family" . "var(--font-body)")
                   ("font-size" . "0.8rem")
                   ("color" . "var(--color-text)")
                   ("line-height" . "1.4")))
  (".event-title a" (("color" . "var(--color-accent-dim)")
                     ("text-decoration" . "none")))
  (".event-title a:hover" (("color" . "var(--color-accent)")))
  (".event-detail" (("font-family" . "var(--font-body)")
                    ("font-size" . "0.75rem")
                    ("color" . "var(--color-muted)")
                    ("margin-top" . "1px")
                    ("overflow" . "hidden")
                    ("text-overflow" . "ellipsis")
                    ("white-space" . "nowrap")))
  (".event-meta" (("display" . "flex")
                  ("flex-direction" . "column")
                  ("align-items" . "flex-end")
                  ("gap" . "2px")
                  ("flex-shrink" . "0")))
  (".event-time" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("color" . "var(--color-muted)")))
  (".event-session" (("font-family" . "var(--font-mono)")
                     ("font-size" . "0.6875rem")
                     ("padding" . "1px 6px")
                     ("border-radius" . "2px")))
  ;; Event list container
  (".event-list" (("display" . "flex")
                  ("flex-direction" . "column")
                  ("gap" . "2px")))
  ;; Event date (for paginated rows)
  (".event-date" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.625rem")
                  ("color" . "var(--color-muted)")
                  ("white-space" . "nowrap")))
  ;; Infinite scroll sentinel
  (".load-more-sentinel" (("padding" . "1.5rem")
                          ("text-align" . "center")))
  (".loading-indicator" (("color" . "var(--color-muted)")
                         ("font-size" . "0.8rem")
                         ("font-family" . "var(--font-mono)")))
  (".load-more-sentinel.htmx-request .loading-indicator" (("opacity" . "0.6"))))
