;;;; KLI Dashboard — Base CSS
;;;; Core styles: nav, metrics, sections, expand panels, scratchpad.
;;;; NO animations — this is a daily-driver tool, UX-first.

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-base

  ;; --- Global Reset ---
  ("*" (("box-sizing" . "border-box")))
  ("body" (("margin" . "0") ("padding" . "0")
           ("background" . "var(--color-background)")
           ("color" . "var(--color-text)")
           ("font-family" . "var(--font-body)")
           ("font-size" . "var(--font-body-size)")
           ("line-height" . "1.5")))
  ("a" (("color" . "var(--color-accent)") ("text-decoration" . "none")))
  ("a:hover" (("text-decoration" . "underline")))

  ;; --- Section Label + Accent Line ---
  (".section-label" (("font-family" . "var(--font-mono)")
                     ("font-size" . "var(--font-caption)")
                     ("letter-spacing" . "0.15em")
                     ("text-transform" . "uppercase")
                     ("color" . "var(--color-muted)")))
  (".accent-line" (("width" . "40px")
                   ("height" . "2px")
                   ("background" . "var(--color-accent)")))
  (".hr-subtle" (("border" . "none")
                 ("height" . "1px")
                 ("background" . "var(--color-border)")
                 ("margin" . "0")))

  ;; === NAVIGATION ===
  (".dashboard-nav" (("display" . "flex")
                     ("align-items" . "center")
                     ("justify-content" . "space-between")
                     ("padding" . "0 2rem")
                     ("height" . "48px")
                     ("border-bottom" . "1px solid var(--color-border)")
                     ("background" . "var(--color-background)")
                     ("position" . "sticky")
                     ("top" . "0")
                     ("z-index" . "50")))
  (".nav-left" (("display" . "flex")
                ("align-items" . "center")
                ("gap" . "2rem")))
  (".nav-brand" (("font-family" . "var(--font-family)")
                 ("font-size" . "0.95rem")
                 ("color" . "var(--color-heading)")
                 ("letter-spacing" . "-0.02em")
                 ("padding-right" . "1.5rem")
                 ("border-right" . "1px solid var(--color-border)")))
  (".nav-links" (("display" . "flex")
                 ("gap" . "0")
                 ("align-items" . "stretch")
                 ("height" . "48px")))
  (".nav-link" (("font-family" . "var(--font-mono)")
                ("font-size" . "0.7rem")
                ("letter-spacing" . "0.1em")
                ("text-transform" . "uppercase")
                ("color" . "var(--color-muted)")
                ("text-decoration" . "none")
                ("padding" . "0 1rem")
                ("display" . "flex")
                ("align-items" . "center")
                ("border-bottom" . "2px solid transparent")
                ("transition" . "color 0.1s ease, border-color 0.1s ease")))
  (".nav-link:hover" (("color" . "var(--color-text)")
                      ("text-decoration" . "none")))
  (".nav-link.active" (("color" . "var(--color-accent)")
                       ("border-bottom-color" . "var(--color-accent)")))
  (".nav-right" (("display" . "flex")
                 ("align-items" . "center")
                 ("gap" . "0.75rem")))
  (".nav-scratchpad-btn" (("background" . "none")
                          ("border" . "1px solid var(--color-border)")
                          ("color" . "var(--color-muted)")
                          ("cursor" . "pointer")
                          ("font-size" . "0.875rem")
                          ("padding" . "2px 8px")
                          ("border-radius" . "2px")
                          ("transition" . "color 0.15s, border-color 0.15s")))
  (".nav-scratchpad-btn:hover" (("color" . "var(--color-accent)")
                                ("border-color" . "var(--color-accent)")))
  (".nav-stat" (("font-family" . "var(--font-mono)")
                ("font-size" . "0.6875rem")
                ("letter-spacing" . "0.05em")
                ("color" . "var(--color-muted)")
                ("padding" . "3px 10px")
                ("border" . "1px solid var(--color-border)")
                ("border-radius" . "2px")))

  ;; === DEPOT TABS ===
  (".depot-tabs" (("display" . "flex")
                  ("gap" . "0.5rem")
                  ("padding-bottom" . "1rem")
                  ("border-bottom" . "1px solid var(--color-border)")
                  ("margin-bottom" . "1.5rem")))
  (".depot-tab" (("font-family" . "var(--font-mono)")
                 ("font-size" . "0.7rem")
                 ("letter-spacing" . "0.08em")
                 ("text-transform" . "uppercase")
                 ("padding" . "0.35rem 0.85rem")
                 ("border" . "1px solid var(--color-border)")
                 ("border-radius" . "2px")
                 ("color" . "var(--color-muted)")
                 ("text-decoration" . "none")
                 ("transition" . "color 0.15s ease, border-color 0.15s ease, background 0.15s ease")))
  (".depot-tab:hover" (("color" . "var(--color-text)")
                       ("border-color" . "var(--color-accent-dim)")
                       ("text-decoration" . "none")))
  (".depot-tab.active" (("color" . "var(--color-accent)")
                        ("border-color" . "var(--color-accent)")
                        ("background" . "rgba(212, 168, 83, 0.06)")))

  ;; === METRICS BAR ===
  (".metrics-bar" (("display" . "grid")
                   ("grid-template-columns" . "repeat(auto-fit, minmax(120px, 1fr))")
                   ("gap" . "1px")
                   ("background" . "var(--color-border)")
                   ("border" . "1px solid var(--color-border)")
                   ("border-radius" . "2px")
                   ("margin-bottom" . "2rem")
                   ("overflow" . "hidden")))
  (".metric" (("display" . "flex")
              ("flex-direction" . "column")
              ("align-items" . "center")
              ("padding" . "1rem 0.75rem")
              ("background" . "var(--color-surface)")))
  (".metric-value" (("font-family" . "var(--font-heading)")
                    ("font-size" . "1.4rem")
                    ("color" . "var(--color-heading)")
                    ("line-height" . "1")))
  (".metric-label" (("font-family" . "var(--font-mono)")
                    ("font-size" . "0.6875rem")
                    ("letter-spacing" . "0.12em")
                    ("text-transform" . "uppercase")
                    ("color" . "var(--color-muted)")
                    ("margin-top" . "0.4rem")))

  ;; === PAGE WRAPPER ===
  (".page-wrapper" (("max-width" . "860px")
                    ("margin" . "0 auto")
                    ("padding" . "1.5rem 2rem")))

  ;; === SECTION HEADER ===
  (".section-head" (("display" . "flex")
                    ("align-items" . "center")
                    ("gap" . "0.75rem")
                    ("margin-bottom" . "1rem")))
  (".section-count" (("font-family" . "var(--font-mono)")
                     ("font-size" . "var(--font-caption)")
                     ("color" . "var(--color-muted)")
                     ("margin-left" . "auto")))
  (".section-cards" (("display" . "flex")
                     ("flex-direction" . "column")
                     ("gap" . "8px")))

  ;; === TAG ===
  (".tag" (("font-family" . "var(--font-mono)")
           ("font-size" . "0.6875rem")
           ("letter-spacing" . "0.06em")
           ("text-transform" . "uppercase")
           ("color" . "var(--color-muted)")
           ("background" . "var(--color-surface-2)")
           ("border" . "1px solid var(--color-border)")
           ("padding" . "2px 8px")
           ("border-radius" . "2px")))

  ;; === EMPTY STATE ===
  (".empty-state" (("text-align" . "center")
                   ("padding" . "2rem 1rem")
                   ("font-family" . "var(--font-body)")
                   ("font-size" . "0.85rem")
                   ("color" . "var(--color-muted)")
                   ("font-style" . "italic")))

  ;; === REVEAL / STAGGER ANIMATIONS ===
  (".reveal" (("opacity" . "0")
              ("transform" . "translateY(12px)")
              ("transition" . "opacity 0.4s ease, transform 0.4s ease")))
  (".reveal.visible" (("opacity" . "1")
                      ("transform" . "translateY(0)")))
  (".stagger" (("opacity" . "0")
               ("transform" . "translateY(8px)")
               ("transition" . "opacity 0.3s ease, transform 0.3s ease")))
  (".stagger.visible" (("opacity" . "1")
                       ("transform" . "translateY(0)"))))
