;;;; KLI Dashboard — Frontier CSS
;;;; Pick Up / Pinned / Inbox / Ready + scratchpad + expand panels.
;;;; UX-first: no animations, proper contrast, immediate readability.

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-frontier

  ;; === FRONTIER SECTIONS ===
  (".frontier-sections" (("display" . "flex")
                         ("flex-direction" . "column")
                         ("gap" . "2rem")))
  (".frontier-section" (("margin" . "0")))
  (".frontier-section h2" (("font-family" . "var(--font-mono)")
                           ("font-size" . "0.7rem")
                           ("font-weight" . "400")
                           ("letter-spacing" . "0.15em")
                           ("text-transform" . "uppercase")
                           ("color" . "var(--color-muted)")
                           ("margin" . "0 0 0.75rem 0")
                           ("display" . "flex")
                           ("align-items" . "center")
                           ("gap" . "0.75rem")))
  (".frontier-section h2 span.count" (("color" . "var(--color-accent-dim)")))

  ;; === PICKUP CARDS ===
  (".pickup-card" (("padding" . "10px 14px")
                   ("border-radius" . "2px")
                   ("border" . "1px solid var(--color-border)")
                   ("background" . "var(--color-surface)")
                   ("transition" . "border-color 0.15s ease")))
  (".pickup-card:hover" (("border-color" . "var(--color-accent-dim)")))
  (".pickup-header" (("display" . "flex")
                     ("align-items" . "center")
                     ("gap" . "8px")
                     ("justify-content" . "space-between")))
  (".pickup-actions" (("display" . "flex")
                      ("align-items" . "center")
                      ("gap" . "4px")
                      ("flex-shrink" . "0")))
  (".pickup-title" (("color" . "var(--color-heading)")
                    ("font-family" . "var(--font-heading)")
                    ("font-size" . "0.85rem")
                    ("font-weight" . "500")
                    ("text-decoration" . "none")))
  (".pickup-title:hover" (("text-decoration" . "underline")))
  (".pickup-summary" (("font-size" . "0.78rem")
                      ("color" . "var(--color-text)")
                      ("margin-top" . "4px")
                      ("line-height" . "1.4")))
  (".pickup-meta" (("display" . "flex")
                   ("gap" . "12px")
                   ("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")
                   ("color" . "var(--color-muted)")
                   ("margin-top" . "8px")))

  ;; === PIN CARDS ===
  (".pin-card" (("display" . "flex")
                ("align-items" . "center")
                ("justify-content" . "space-between")
                ("padding" . "6px 12px")
                ("border-radius" . "2px")
                ("border" . "1px solid var(--color-border)")
                ("background" . "var(--color-surface)")
                ("transition" . "border-color 0.15s ease")))
  (".pin-card:hover" (("border-color" . "var(--color-accent-dim)")))
  (".pin-title" (("color" . "var(--color-heading)")
                 ("font-size" . "0.8rem")
                 ("text-decoration" . "none")))
  (".pin-title:hover" (("text-decoration" . "underline")))

  ;; === PIN TOGGLE BUTTON ===
  (".pin-btn" (("background" . "none")
               ("border" . "none")
               ("color" . "var(--color-muted)")
               ("cursor" . "pointer")
               ("font-size" . "14px")
               ("padding" . "2px 4px")
               ("line-height" . "1")
               ("transition" . "color 0.1s ease")))
  (".pin-btn:hover" (("color" . "var(--color-accent)")))
  (".pin-btn.pinned" (("color" . "var(--color-accent)")))

  ;; === DEPOT BADGE ===
  (".depot-badge" (("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")
                   ("letter-spacing" . "0.06em")
                   ("text-transform" . "uppercase")
                   ("padding" . "1px 6px")
                   ("border-radius" . "2px")
                   ("border" . "1px solid var(--color-border)")
                   ("color" . "var(--color-muted)")))

  ;; === INBOX CARDS ===
  (".inbox-card" (("padding" . "8px 12px")
                  ("border-radius" . "2px")
                  ("border" . "1px solid var(--color-border)")
                  ("background" . "var(--color-surface)")
                  ("transition" . "border-color 0.15s ease")))
  (".inbox-card:hover" (("border-color" . "var(--color-accent-dim)")))
  (".inbox-header" (("display" . "flex")
                    ("align-items" . "center")
                    ("justify-content" . "space-between")
                    ("gap" . "8px")))
  (".inbox-title" (("color" . "var(--color-heading)")
                   ("font-size" . "0.8rem")
                   ("text-decoration" . "none")))
  (".inbox-title:hover" (("text-decoration" . "underline")))
  (".inbox-meta" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("color" . "var(--color-muted)")
                  ("margin-top" . "4px")))

  ;; === READY TO WORK — TOPIC GROUPS ===
  (".topic-group" (("margin-bottom" . "1rem")))
  (".topic-name" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.7rem")
                  ("font-weight" . "400")
                  ("letter-spacing" . "0.1em")
                  ("text-transform" . "uppercase")
                  ("margin" . "0 0 6px 0")))
  (".topic-cards" (("display" . "flex")
                   ("flex-direction" . "column")
                   ("gap" . "4px")
                   ("padding-left" . "12px")
                   ("border-left" . "2px solid var(--color-border)")))
  (".ready-card" (("display" . "flex")
                  ("align-items" . "center")
                  ("gap" . "8px")
                  ("padding" . "4px 8px")
                  ("border-radius" . "2px")))
  (".ready-card:hover" (("background" . "var(--color-surface)")))
  (".ready-card a" (("color" . "var(--color-text)")
                    ("font-size" . "0.8rem")
                    ("text-decoration" . "none")))
  (".ready-card a:hover" (("color" . "var(--color-heading)")
                          ("text-decoration" . "underline")))

  ;; === EXPAND BUTTON ===
  (".expand-btn" (("background" . "none")
                  ("border" . "none")
                  ("color" . "var(--color-muted)")
                  ("cursor" . "pointer")
                  ("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("padding" . "3px 6px")
                  ("border-radius" . "2px")
                  ("margin-top" . "4px")))
  (".expand-btn:hover" (("color" . "var(--color-text)")
                        ("background" . "var(--color-surface-2)")))
  (".expand-btn.open" (("color" . "var(--color-accent)")))
  (".expand-btn.loading" (("color" . "var(--color-muted)")
                          ("opacity" . "0.6")))
  (".expand-btn-sm" (("margin-top" . "0")
                     ("padding" . "2px 4px")
                     ("font-size" . "0.6875rem")))

  ;; === EXPAND TARGET (hidden until loaded) ===
  (".expand-target:empty" (("display" . "none")))

  ;; === EXPAND PANEL (loaded via HTMX) ===
  (".expand-panel" (("margin-top" . "8px")
                    ("padding" . "10px 14px")
                    ("border-top" . "1px solid var(--color-border)")
                    ("font-size" . "0.78rem")
                    ("line-height" . "1.5")))
  (".expand-section" (("margin-bottom" . "8px")))
  (".expand-inline" (("margin-bottom" . "4px")))
  (".expand-label" (("font-family" . "var(--font-mono)")
                    ("font-size" . "0.6875rem")
                    ("font-weight" . "400")
                    ("color" . "var(--color-muted)")
                    ("text-transform" . "uppercase")
                    ("letter-spacing" . "0.08em")
                    ("margin-bottom" . "3px")))
  (".expand-desc" (("color" . "var(--color-text)")))
  (".expand-goals" (("margin" . "0") ("padding-left" . "16px")
                    ("color" . "var(--color-text)")))
  (".expand-goals li" (("margin-bottom" . "2px")))
  (".expand-phase" (("color" . "var(--color-accent)")
                    ("font-weight" . "500")))
  (".expand-children" (("margin" . "0") ("padding-left" . "16px")))
  (".expand-children a" (("color" . "var(--color-accent)")
                         ("text-decoration" . "none")
                         ("font-size" . "0.78rem")))
  (".expand-children a:hover" (("text-decoration" . "underline")))
  (".expand-handoff" (("background" . "var(--color-surface-2)")
                      ("padding" . "8px 10px")
                      ("border-radius" . "2px")
                      ("font-family" . "var(--font-mono)")
                      ("font-size" . "0.7rem")
                      ("color" . "var(--color-text)")
                      ("overflow-x" . "auto")
                      ("white-space" . "pre-wrap")
                      ("word-break" . "break-word")
                      ("max-height" . "160px")
                      ("overflow-y" . "auto")
                      ("margin" . "0")))
  (".expand-obs" (("margin-bottom" . "6px")
                  ("padding-left" . "8px")
                  ("border-left" . "2px solid var(--color-border)")))
  (".expand-obs-time" (("font-family" . "var(--font-mono)")
                       ("font-size" . "0.6875rem")
                       ("color" . "var(--color-muted)")
                       ("display" . "block")
                       ("margin-bottom" . "1px")))
  (".expand-obs-text" (("color" . "var(--color-text)")
                       ("font-size" . "0.72rem")))
  (".expand-footer" (("margin-top" . "6px")
                     ("padding-top" . "4px")
                     ("border-top" . "1px solid var(--color-border)")))
  (".expand-detail-link" (("color" . "var(--color-accent)")
                          ("font-size" . "0.72rem")))

  ;; === SCRATCHPAD OPEN BUTTON (inline in card actions) ===
  (".scratchpad-open-btn" (("background" . "none")
                           ("border" . "none")
                           ("color" . "var(--color-muted)")
                           ("cursor" . "pointer")
                           ("font-size" . "14px")
                           ("padding" . "2px 6px")
                           ("transition" . "color 0.1s ease")))
  (".scratchpad-open-btn:hover" (("color" . "var(--color-accent)")))

  ;; === SCRATCHPAD SIDEBAR ===
  (".scratchpad-sidebar" (("position" . "fixed")
                          ("top" . "0")
                          ("right" . "-380px")
                          ("width" . "380px")
                          ("height" . "100vh")
                          ("z-index" . "200")
                          ("background" . "var(--color-surface)")
                          ("border-left" . "1px solid var(--color-border)")
                          ("display" . "flex")
                          ("flex-direction" . "column")
                          ("transition" . "right 0.2s ease")))
  (".scratchpad-sidebar.open" (("right" . "0")))
  (".scratchpad-header" (("display" . "flex")
                         ("align-items" . "center")
                         ("justify-content" . "space-between")
                         ("padding" . "12px 16px")
                         ("border-bottom" . "1px solid var(--color-border)")
                         ("font-family" . "var(--font-mono)")
                         ("font-size" . "0.7rem")
                         ("letter-spacing" . "0.1em")
                         ("text-transform" . "uppercase")
                         ("color" . "var(--color-heading)")))
  (".scratchpad-close" (("background" . "none")
                        ("border" . "none")
                        ("color" . "var(--color-muted)")
                        ("cursor" . "pointer")
                        ("font-size" . "14px")
                        ("padding" . "4px 6px")))
  (".scratchpad-close:hover" (("color" . "var(--color-heading)")))
  ("#scratchpad-form" (("flex" . "1")
                       ("display" . "flex")
                       ("flex-direction" . "column")
                       ("min-height" . "0")))
  (".scratchpad-textarea" (("flex" . "1")
                           ("width" . "100%")
                           ("padding" . "12px 16px")
                           ("background" . "transparent")
                           ("border" . "none")
                           ("color" . "var(--color-text)")
                           ("font-family" . "var(--font-mono)")
                           ("font-size" . "0.78rem")
                           ("line-height" . "1.6")
                           ("resize" . "none")
                           ("outline" . "none")))
  (".scratchpad-textarea::placeholder" (("color" . "var(--color-muted)")))
  (".scratchpad-status" (("padding" . "6px 16px")
                         ("font-family" . "var(--font-mono)")
                         ("font-size" . "0.6875rem")
                         ("color" . "var(--color-success)")
                         ("min-height" . "24px")))
  (".scratchpad-error" (("color" . "var(--color-error)"))))
