;;;; KLI Dashboard — Graph Page CSS Module
;;;; WebGL/Pixi.js graph: detail panel, legend, controls, sliders.
;;;; KLI token convention (--color-*, --font-*).

(in-package :kli-dashboard)

(defcss :kli-graph

  ;; Graph fills viewport — flex column so depot-tabs push container down
  (".graph-board" (("padding" . "0") ("margin" . "0") ("overflow" . "hidden")
                   ("max-width" . "none")
                   ("display" . "flex") ("flex-direction" . "column")
                   ("height" . "calc(100vh - 48px)")))
  (".graph-board .depot-tabs" (("position" . "fixed") ("top" . "60px") ("right" . "24px")
                               ("z-index" . "20") ("padding" . "0")
                               ("margin" . "0") ("border-bottom" . "none")
                               ("gap" . "4px") ("flex-wrap" . "wrap")
                               ("justify-content" . "flex-end")))
  ("#graph-container" (("position" . "relative") ("flex" . "1") ("min-height" . "0")
                       ("overflow" . "hidden")))
  ("#graph-container canvas" (("display" . "block")))

  ;; Detail panel — the ONE place where box-shadow is permitted
  ("#detail-panel" (("display" . "none") ("position" . "fixed")
                    ("top" . "100px") ("right" . "24px") ("width" . "320px")
                    ("max-height" . "calc(100vh - 100px)") ("overflow-y" . "auto")
                    ("background" . "var(--color-surface)")
                    ("border" . "1px solid var(--color-border)")
                    ("border-radius" . "2px") ("padding" . "16px")
                    ("z-index" . "10") ("box-shadow" . "0 4px 12px rgba(0,0,0,0.4)")))
  ("#detail-panel h3" (("color" . "var(--color-heading)") ("font-family" . "var(--font-heading)")
                       ("font-size" . "0.85rem")
                       ("margin" . "0 0 4px 0") ("padding-right" . "24px")))
  ("#detail-panel .card-id" (("font-size" . "0.6875rem") ("color" . "var(--color-muted)")
                             ("font-family" . "var(--font-mono)") ("margin-bottom" . "12px")))
  (".detail-row" (("display" . "flex") ("justify-content" . "space-between")
                  ("font-size" . "0.78rem") ("padding" . "4px 0")
                  ("border-bottom" . "1px solid var(--color-border)")))
  (".detail-label" (("color" . "var(--color-muted)") ("font-family" . "var(--font-mono)")
                    ("font-size" . "0.6875rem") ("letter-spacing" . "0.06em")
                    ("text-transform" . "uppercase")))
  (".detail-value" (("color" . "var(--color-text)")))
  (".status-badge" (("padding" . "1px 8px") ("border-radius" . "2px")
                    ("font-size" . "0.6875rem") ("font-family" . "var(--font-mono)")
                    ("letter-spacing" . "0.04em")))
  (".status-recent" (("background" . "rgba(74,222,128,0.15)") ("color" . "var(--color-success)")))
  (".status-event-sourced" (("background" . "rgba(163,113,247,0.15)") ("color" . "#a371f7")))
  (".status-dormant" (("background" . "rgba(123,123,137,0.15)") ("color" . "var(--color-muted)")))
  (".status-completed" (("background" . "rgba(74,222,128,0.15)") ("color" . "var(--color-success)")))
  (".status-active" (("background" . "rgba(163,113,247,0.15)") ("color" . "#a371f7")))
  (".detail-link" (("display" . "block") ("margin-top" . "12px")
                   ("color" . "var(--color-accent)") ("text-decoration" . "none")
                   ("font-size" . "0.78rem") ("font-family" . "var(--font-mono)")))
  (".detail-link:hover" (("text-decoration" . "underline")))
  (".detail-close" (("position" . "absolute") ("top" . "12px") ("right" . "12px")
                    ("background" . "none") ("border" . "none")
                    ("color" . "var(--color-muted)") ("cursor" . "pointer")
                    ("font-size" . "0.875rem") ("padding" . "4px 8px")))
  (".detail-close:hover" (("color" . "var(--color-heading)")))

  ;; Panel action buttons (complete/reopen)
  (".panel-actions" (("margin-top" . "12px") ("padding-top" . "8px")
                     ("border-top" . "1px solid var(--color-border)")
                     ("display" . "flex") ("gap" . "8px")))
  (".panel-action-btn" (("flex" . "1") ("padding" . "6px 12px")
                        ("font-size" . "0.6875rem") ("font-family" . "var(--font-mono)")
                        ("letter-spacing" . "0.04em") ("text-transform" . "uppercase")
                        ("background" . "var(--color-background)")
                        ("color" . "var(--color-text)")
                        ("border" . "1px solid var(--color-border)")
                        ("border-radius" . "2px") ("cursor" . "pointer")))
  (".panel-action-btn:hover" (("border-color" . "var(--color-accent)")
                              ("color" . "var(--color-accent)")))
  (".panel-complete-btn" (("border-color" . "var(--color-success)")
                          ("color" . "var(--color-success)")))
  (".panel-complete-btn:hover" (("background" . "rgba(74,222,128,0.08)")))

  ;; Edge detail in panel (with sever buttons)
  (".detail-edges" (("margin-top" . "8px") ("padding-top" . "8px")
                    ("border-top" . "1px solid var(--color-border)")))
  (".edge-section" (("margin" . "4px 0")))
  (".edge-dir" (("font-size" . "0.6875rem") ("color" . "var(--color-muted)")
                ("font-family" . "var(--font-mono)") ("letter-spacing" . "0.06em")
                ("text-transform" . "uppercase")
                ("display" . "block") ("margin-bottom" . "2px")))
  (".edge-group-detail" (("font-size" . "0.75rem") ("padding" . "2px 0 4px 12px")))
  (".edge-layer" (("font-family" . "var(--font-mono)") ("display" . "block")
                  ("margin-bottom" . "2px")))
  (".edge-target-row" (("display" . "flex") ("justify-content" . "space-between")
                       ("align-items" . "center") ("padding" . "1px 0")))
  (".edge-target-link" (("color" . "var(--color-text)") ("text-decoration" . "none")
                        ("font-size" . "0.6875rem") ("font-family" . "var(--font-mono)")
                        ("overflow" . "hidden") ("text-overflow" . "ellipsis")
                        ("white-space" . "nowrap") ("max-width" . "220px")))
  (".edge-target-link:hover" (("color" . "var(--color-accent)")))
  (".edge-sever-btn" (("background" . "none") ("border" . "1px solid transparent")
                      ("color" . "var(--color-muted)") ("cursor" . "pointer")
                      ("font-size" . "0.75rem") ("padding" . "0 4px")
                      ("border-radius" . "2px") ("flex-shrink" . "0")))
  (".edge-sever-btn:hover" (("color" . "#f85149") ("border-color" . "#f85149")))

  ;; Cluster legend
  ("#cluster-legend" (("position" . "fixed") ("bottom" . "24px") ("left" . "24px")
                      ("background" . "var(--color-surface)")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px") ("padding" . "12px 16px")
                      ("z-index" . "10") ("max-height" . "300px")
                      ("overflow-y" . "auto")))
  ("#cluster-legend h4" (("font-size" . "0.6875rem") ("color" . "var(--color-muted)")
                         ("font-family" . "var(--font-mono)") ("letter-spacing" . "0.08em")
                         ("text-transform" . "uppercase")
                         ("margin" . "0 0 8px 0")))
  (".legend-item" (("display" . "flex") ("align-items" . "center") ("gap" . "8px")
                   ("font-size" . "0.75rem") ("color" . "var(--color-text)")
                   ("font-family" . "var(--font-mono)")
                   ("padding" . "2px 0")))
  (".legend-dot" (("width" . "10px") ("height" . "10px") ("border-radius" . "50%")
                  ("flex-shrink" . "0") ("display" . "inline-block")))

  ;; Layer controls panel
  ("#graph-controls" (("position" . "fixed") ("top" . "60px") ("left" . "24px")
                      ("z-index" . "20") ("background" . "var(--color-surface)")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px") ("padding" . "10px 14px")
                      ("max-height" . "calc(100vh - 100px)") ("overflow-y" . "auto")))
  (".layer-toggles label" (("display" . "flex") ("align-items" . "center")
                           ("gap" . "6px") ("font-size" . "0.75rem")
                           ("color" . "var(--color-text)") ("padding" . "3px 0")
                           ("font-family" . "var(--font-mono)")
                           ("cursor" . "pointer")))
  (".layer-toggles input[type=checkbox]" (("accent-color" . "var(--color-accent)")))
  (".toggle-group-label" (("font-size" . "0.625rem") ("color" . "var(--color-muted)")
                          ("font-family" . "var(--font-mono)")
                          ("text-transform" . "uppercase") ("letter-spacing" . "0.08em")
                          ("padding" . "6px 0 2px 0") ("margin-top" . "4px")
                          ("border-top" . "1px solid var(--color-border)")))
  (".toggle-group-label:first-child" (("border-top" . "none") ("margin-top" . "0")
                                      ("padding-top" . "0")))

  ;; Search
  (".graph-search" (("margin-bottom" . "8px")))
  ("#graph-search" (("width" . "100%") ("padding" . "6px 8px")
                    ("background" . "var(--color-background)")
                    ("border" . "1px solid var(--color-border)")
                    ("border-radius" . "2px") ("color" . "var(--color-text)")
                    ("font-size" . "0.75rem") ("font-family" . "var(--font-mono)")
                    ("box-sizing" . "border-box")))
  ("#graph-search::placeholder" (("color" . "var(--color-muted)")))
  ("#graph-search:focus" (("outline" . "none") ("border-color" . "var(--color-accent)")))

  ;; Graph action buttons
  (".graph-actions" (("display" . "flex") ("gap" . "6px") ("margin-top" . "8px")
                     ("padding-top" . "8px") ("border-top" . "1px solid var(--color-border)")))
  (".graph-btn" (("flex" . "1") ("padding" . "4px 8px") ("font-size" . "0.6875rem")
                 ("font-family" . "var(--font-mono)") ("letter-spacing" . "0.04em")
                 ("background" . "var(--color-background)") ("color" . "var(--color-text)")
                 ("border" . "1px solid var(--color-border)") ("border-radius" . "2px")
                 ("cursor" . "pointer") ("text-transform" . "uppercase")))
  (".graph-btn:hover" (("border-color" . "var(--color-accent-dim)")))
  (".graph-btn.active" (("background" . "rgba(212,168,83,0.08)")
                        ("border-color" . "var(--color-accent)")
                        ("color" . "var(--color-accent)")))

  ;; Force parameter sliders
  (".force-sliders" (("margin-top" . "8px") ("padding-top" . "8px")
                     ("border-top" . "1px solid var(--color-border)")))
  (".slider-row" (("display" . "flex") ("align-items" . "center") ("gap" . "8px")
                  ("padding" . "4px 0") ("font-size" . "0.6875rem")))
  (".slider-row label" (("color" . "var(--color-muted)") ("width" . "55px")
                        ("flex-shrink" . "0") ("font-family" . "var(--font-mono)")))
  (".slider-row input[type=range]" (("flex" . "1") ("height" . "4px")
                                    ("accent-color" . "var(--color-accent)")
                                    ("cursor" . "pointer")))
  (".slider-val" (("color" . "var(--color-text)") ("font-family" . "var(--font-mono)")
                  ("font-size" . "0.625rem") ("width" . "40px") ("text-align" . "right"))))
