;;;; KLI Dashboard — Health page CSS

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-health
  (".health-summary" (("display" . "flex")
                      ("justify-content" . "space-between")
                      ("align-items" . "center")
                      ("padding" . "1.25rem 1.5rem")
                      ("background" . "var(--color-surface)")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px")
                      ("margin-bottom" . "2rem")))
  (".health-status" (("font-family" . "var(--font-heading)")
                     ("font-size" . "1.1rem")
                     ("display" . "flex")
                     ("align-items" . "center")
                     ("gap" . "0.75rem")))
  (".health-stats" (("display" . "flex")
                    ("gap" . "1.5rem")
                    ("font-family" . "var(--font-mono)")
                    ("font-size" . "0.7rem")
                    ("color" . "var(--color-muted)")))
  (".health-section" (("background" . "var(--color-surface)")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px")
                      ("margin-bottom" . "1rem")
                      ("overflow" . "hidden")
                      ("transition" . "border-color 0.15s ease")))
  (".health-section.warn" (("border-left" . "2px solid var(--color-accent)")))
  (".health-section.error" (("border-left" . "2px solid var(--color-error)")))
  (".health-section.ok" (("border-left" . "2px solid var(--color-success)")))
  (".health-header" (("display" . "flex")
                     ("align-items" . "center")
                     ("gap" . "1rem")
                     ("padding" . "1rem 1.25rem")))
  (".health-icon" (("font-size" . "1.1rem")
                   ("flex-shrink" . "0")))
  (".health-title" (("flex" . "1")))
  (".health-title h3" (("font-family" . "var(--font-heading)")
                       ("font-size" . "0.85rem")
                       ("color" . "var(--color-heading)")
                       ("margin" . "0")))
  (".health-desc" (("font-family" . "var(--font-body)")
                   ("font-size" . "0.75rem")
                   ("color" . "var(--color-muted)")
                   ("margin-top" . "2px")))
  (".health-badge" (("font-family" . "var(--font-mono)")
                    ("font-size" . "0.7rem")
                    ("font-weight" . "600")
                    ("padding" . "2px 10px")
                    ("border-radius" . "2px")
                    ("border" . "1px solid")
                    ("flex-shrink" . "0"))))
