;;;; KLI Dashboard — Health page CSS

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-health
  (".health-summary" (("display" . "flex")
                      ("justify-content" . "space-between")
                      ("align-items" . "center")
                      ("padding" . "1.25rem 1.5rem")
                      ("background" . "var(--color-surface)")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px")
                      ("margin-bottom" . "2rem")))
  (".health-status" (("font-family" . "var(--font-heading)")
                     ("font-size" . "1.1rem")
                     ("display" . "flex")
                     ("align-items" . "center")
                     ("gap" . "0.75rem")))
  (".health-stats" (("display" . "flex")
                    ("gap" . "1.5rem")
                    ("font-family" . "var(--font-mono)")
                    ("font-size" . "0.7rem")
                    ("color" . "var(--color-muted)")))
  (".health-section" (("background" . "var(--color-surface)")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px")
                      ("margin-bottom" . "1rem")
                      ("overflow" . "hidden")
                      ("transition" . "border-color 0.15s ease")))
  (".health-section.warn" (("border-left" . "2px solid var(--color-accent)")))
  (".health-section.error" (("border-left" . "2px solid var(--color-error)")))
  (".health-section.ok" (("border-left" . "2px solid var(--color-success)")))
  (".health-details" (("width" . "100%")))
  (".health-details summary" (("cursor" . "pointer")
                               ("list-style" . "none")))
  (".health-details summary::-webkit-details-marker" (("display" . "none")))
  (".health-details summary::marker" (("display" . "none")))
  (".health-header" (("display" . "flex")
                     ("align-items" . "center")
                     ("gap" . "1rem")
                     ("padding" . "1rem 1.25rem")))
  (".health-label" (("font-family" . "var(--font-mono)")
                    ("font-size" . "0.6rem")
                    ("font-weight" . "600")
                    ("letter-spacing" . "0.05em")
                    ("color" . "var(--color-muted)")
                    ("background" . "var(--color-bg)")
                    ("padding" . "2px 8px")
                    ("border-radius" . "2px")
                    ("border" . "1px solid var(--color-border)")
                    ("flex-shrink" . "0")
                    ("min-width" . "4.5rem")
                    ("text-align" . "center")))
  (".health-title" (("flex" . "1")))
  (".health-title h3" (("font-family" . "var(--font-heading)")
                       ("font-size" . "0.85rem")
                       ("color" . "var(--color-heading)")
                       ("margin" . "0")))
  (".health-desc" (("font-family" . "var(--font-body)")
                   ("font-size" . "0.75rem")
                   ("color" . "var(--color-muted)")
                   ("margin-top" . "2px")))
  (".health-badge" (("font-family" . "var(--font-mono)")
                    ("font-size" . "0.7rem")
                    ("font-weight" . "600")
                    ("padding" . "2px 10px")
                    ("border-radius" . "2px")
                    ("border" . "1px solid")
                    ("flex-shrink" . "0")))
  (".health-body" (("border-top" . "1px solid var(--color-border)")
                   ("padding" . "0.75rem 1.25rem")))
  (".health-items" (("list-style" . "none")
                    ("margin" . "0")
                    ("padding" . "0")
                    ("display" . "flex")
                    ("flex-direction" . "column")
                    ("gap" . "0.25rem")))
  (".health-item" (("font-family" . "var(--font-mono)")
                   ("font-size" . "0.75rem")
                   ("padding" . "0.35rem 0.5rem")
                   ("border-radius" . "2px")
                   ("transition" . "background 0.1s ease")))
  (".health-item:hover" (("background" . "var(--color-bg)")))
  (".health-item-link" (("color" . "var(--color-text)")
                        ("text-decoration" . "none")
                        ("border-bottom" . "1px solid var(--color-border)")))
  (".health-item-link:hover" (("color" . "var(--color-accent)")
                               ("border-bottom-color" . "var(--color-accent)")))
  (".health-suggested" (("display" . "flex")
                        ("align-items" . "center")
                        ("justify-content" . "space-between")
                        ("gap" . "0.75rem")
                        ("width" . "100%")))
  (".health-suggested-pair" (("display" . "flex")
                              ("align-items" . "center")
                              ("gap" . "0.5rem")
                              ("flex" . "1")
                              ("min-width" . "0")))
  (".health-edge-type" (("font-family" . "var(--font-mono)")
                        ("font-size" . "0.6rem")
                        ("color" . "var(--color-muted)")
                        ("background" . "var(--color-bg)")
                        ("padding" . "1px 6px")
                        ("border-radius" . "2px")
                        ("border" . "1px solid var(--color-border)")
                        ("flex-shrink" . "0")))
  (".health-arrow" (("color" . "var(--color-muted)")
                    ("font-size" . "0.7rem")
                    ("flex-shrink" . "0")))
  (".health-actions" (("display" . "flex")
                      ("gap" . "0.5rem")
                      ("flex-shrink" . "0")))
  (".health-btn" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.65rem")
                  ("font-weight" . "600")
                  ("padding" . "3px 10px")
                  ("border-radius" . "2px")
                  ("border" . "1px solid var(--color-border)")
                  ("background" . "var(--color-bg)")
                  ("color" . "var(--color-text)")
                  ("cursor" . "pointer")
                  ("transition" . "all 0.1s ease")))
  (".health-btn:hover" (("border-color" . "var(--color-text)")))
  (".health-btn:disabled" (("opacity" . "0.5")
                            ("cursor" . "default")))
  (".health-btn-accept:hover" (("color" . "var(--color-success)")
                                ("border-color" . "var(--color-success)")))
  (".health-btn-dismiss:hover" (("color" . "var(--color-muted)")
                                 ("border-color" . "var(--color-muted)"))))
