;;;; KLI Dashboard — Plan & Clusters CSS
;;;; Phase cards, progress bars, cluster groups, density metrics.

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-plan

  ;; === PLAN HEADER ===
  (".plan-header" (("margin-bottom" . "1.5rem")))
  (".plan-title" (("font-family" . "var(--font-heading)")
                  ("font-size" . "1.1rem")
                  ("font-weight" . "500")
                  ("color" . "var(--color-heading)")
                  ("margin" . "0 0 4px 0")))
  (".plan-meta" (("display" . "flex")
                 ("gap" . "12px")
                 ("align-items" . "center")
                 ("font-family" . "var(--font-mono)")
                 ("font-size" . "0.6875rem")
                 ("color" . "var(--color-muted)")))
  (".plan-meta a" (("color" . "var(--color-accent)")
                   ("text-decoration" . "none")))
  (".plan-meta a:hover" (("text-decoration" . "underline")))

  ;; === PROGRESS BAR ===
  (".plan-progress" (("display" . "flex")
                     ("align-items" . "center")
                     ("gap" . "12px")
                     ("margin-bottom" . "1.5rem")
                     ("padding" . "10px 14px")
                     ("background" . "var(--color-surface)")
                     ("border" . "1px solid var(--color-border)")
                     ("border-radius" . "2px")))
  (".plan-progress-stat" (("text-align" . "center")
                          ("flex-shrink" . "0")))
  (".plan-progress-stat .count" (("font-family" . "var(--font-heading)")
                                 ("font-size" . "1rem")
                                 ("font-weight" . "500")))
  (".plan-progress-stat .label" (("font-family" . "var(--font-mono)")
                                 ("font-size" . "0.6875rem")
                                 ("color" . "var(--color-muted)")
                                 ("text-transform" . "uppercase")
                                 ("letter-spacing" . "0.08em")))
  (".plan-progress-bar" (("flex" . "1")
                         ("height" . "8px")
                         ("background" . "var(--color-surface-2)")
                         ("border-radius" . "2px")
                         ("overflow" . "hidden")))
  (".plan-progress-fill" (("height" . "100%")
                          ("background" . "var(--color-success)")
                          ("border-radius" . "2px")
                          ("transition" . "width 0.15s ease")))

  ;; === PHASE CARDS ===
  (".plan-phases" (("display" . "flex")
                   ("flex-direction" . "column")
                   ("gap" . "4px")
                   ("margin-bottom" . "1.5rem")))
  (".plan-phases.collapsed .phase-card" (("display" . "none")))
  (".plan-phases.collapsed .collapsed-body" (("display" . "none")))
  (".plan-phases.collapsed .plan-index-card" (("display" . "none")))
  (".plan-phases-header" (("display" . "flex")
                          ("align-items" . "center")
                          ("justify-content" . "space-between")
                          ("margin-bottom" . "8px")))
  (".plan-phases-header h2" (("font-family" . "var(--font-mono)")
                             ("font-size" . "0.7rem")
                             ("font-weight" . "400")
                             ("letter-spacing" . "0.15em")
                             ("text-transform" . "uppercase")
                             ("color" . "var(--color-muted)")
                             ("margin" . "0")))

  (".phase-card" (("border" . "1px solid var(--color-border)")
                  ("border-radius" . "2px")
                  ("background" . "var(--color-surface)")
                  ("transition" . "border-color 0.15s ease")))
  (".phase-card:hover" (("border-color" . "var(--color-accent-dim)")))

  (".phase-card-header" (("display" . "flex")
                         ("align-items" . "center")
                         ("gap" . "10px")
                         ("padding" . "8px 12px")
                         ("cursor" . "pointer")))
  (".phase-status" (("width" . "28px")
                    ("height" . "28px")
                    ("border-radius" . "50%")
                    ("display" . "flex")
                    ("align-items" . "center")
                    ("justify-content" . "center")
                    ("font-size" . "12px")
                    ("flex-shrink" . "0")))
  (".phase-status.completed" (("background" . "rgba(74,222,128,0.15)")
                              ("color" . "var(--color-success)")))
  (".phase-status.ready" (("background" . "rgba(88,166,255,0.12)")
                          ("color" . "#58a6ff")))
  (".phase-status.pending" (("background" . "var(--color-surface-2)")
                            ("color" . "var(--color-muted)")))

  (".phase-info" (("flex" . "1")
                  ("min-width" . "0")))
  (".phase-name" (("font-family" . "var(--font-heading)")
                  ("font-size" . "0.85rem")
                  ("font-weight" . "500")
                  ("color" . "var(--color-heading)")
                  ("white-space" . "nowrap")
                  ("overflow" . "hidden")
                  ("text-overflow" . "ellipsis")))
  (".phase-desc-preview" (("font-size" . "0.75rem")
                          ("color" . "var(--color-muted)")
                          ("margin-top" . "2px")
                          ("white-space" . "nowrap")
                          ("overflow" . "hidden")
                          ("text-overflow" . "ellipsis")))

  (".phase-indicators" (("display" . "flex")
                        ("gap" . "8px")
                        ("align-items" . "center")
                        ("flex-shrink" . "0")))
  (".phase-indicator" (("font-family" . "var(--font-mono)")
                       ("font-size" . "0.6875rem")
                       ("color" . "var(--color-muted)")))
  (".phase-expand-icon" (("color" . "var(--color-muted)")
                         ("font-size" . "10px")
                         ("transition" . "transform 0.1s ease")))
  (".phase-card.open .phase-expand-icon" (("transform" . "rotate(90deg)")))

  ;; === PHASE CARD BODY (expanded) ===
  (".phase-card-body" (("padding" . "0 12px 10px 50px")
                       ("border-top" . "1px solid var(--color-border)")
                       ("font-size" . "0.78rem")
                       ("line-height" . "1.5")))
  (".phase-section" (("margin-bottom" . "8px")))
  (".phase-section-label" (("font-family" . "var(--font-mono)")
                           ("font-size" . "0.6875rem")
                           ("font-weight" . "400")
                           ("color" . "var(--color-muted)")
                           ("text-transform" . "uppercase")
                           ("letter-spacing" . "0.08em")
                           ("margin-bottom" . "3px")))
  (".phase-description" (("color" . "var(--color-text)")))

  (".phase-dep-list" (("display" . "flex")
                      ("flex-wrap" . "wrap")
                      ("gap" . "4px")))
  (".phase-dep-tag" (("display" . "inline-flex")
                     ("align-items" . "center")
                     ("gap" . "4px")
                     ("padding" . "2px 8px")
                     ("border-radius" . "2px")
                     ("background" . "rgba(88,166,255,0.12)")
                     ("color" . "#58a6ff")
                     ("font-size" . "0.72rem")
                     ("font-family" . "var(--font-mono)")))
  (".phase-dep-empty" (("color" . "var(--color-muted)")
                       ("font-size" . "0.72rem")))

  (".phase-edge-list" (("display" . "flex")
                       ("flex-wrap" . "wrap")
                       ("gap" . "4px")))
  (".phase-edge-tag" (("display" . "inline-flex")
                      ("align-items" . "center")
                      ("gap" . "4px")
                      ("padding" . "2px 8px")
                      ("border-radius" . "2px")
                      ("background" . "rgba(163,113,247,0.12)")
                      ("color" . "#a371f7")
                      ("font-size" . "0.72rem")
                      ("font-family" . "var(--font-mono)")))
  (".edge-type" (("font-weight" . "500")))

  (".phase-obs-list" (("display" . "flex")
                      ("flex-direction" . "column")
                      ("gap" . "4px")))
  (".phase-obs-item" (("padding-left" . "8px")
                      ("border-left" . "2px solid var(--color-border)")
                      ("font-size" . "0.72rem")
                      ("color" . "var(--color-text)")))

  (".phase-actions" (("display" . "flex")
                     ("gap" . "8px")
                     ("margin-top" . "8px")
                     ("padding-top" . "8px")
                     ("border-top" . "1px solid var(--color-border)")))
  (".phase-action-btn" (("background" . "none")
                        ("border" . "1px solid var(--color-border)")
                        ("color" . "var(--color-text)")
                        ("font-family" . "var(--font-mono)")
                        ("font-size" . "0.6875rem")
                        ("padding" . "4px 10px")
                        ("border-radius" . "2px")
                        ("cursor" . "pointer")
                        ("text-decoration" . "none")
                        ("transition" . "border-color 0.1s ease")))
  (".phase-action-btn:hover" (("border-color" . "var(--color-accent-dim)")
                              ("color" . "var(--color-accent)")))
  (".phase-action-complete" (("border-color" . "var(--color-success)")
                             ("color" . "var(--color-success)")))

  ;; === PLAN INDEX (task listing) ===
  (".plan-index-card" (("display" . "flex")
                       ("align-items" . "center")
                       ("gap" . "12px")
                       ("padding" . "10px 14px")
                       ("border" . "1px solid var(--color-border)")
                       ("border-radius" . "2px")
                       ("background" . "var(--color-surface)")
                       ("text-decoration" . "none")
                       ("transition" . "border-color 0.15s ease")))
  (".plan-index-card:hover" (("border-color" . "var(--color-accent-dim)")))
  (".plan-index-status" (("flex-shrink" . "0")
                         ("font-family" . "var(--font-mono)")
                         ("font-size" . "0.8rem")
                         ("font-weight" . "500")))
  (".plan-index-info" (("flex" . "1")
                       ("min-width" . "0")))
  (".plan-index-name" (("color" . "var(--color-heading)")
                       ("font-family" . "var(--font-heading)")
                       ("font-size" . "0.85rem")))
  (".plan-index-meta" (("font-family" . "var(--font-mono)")
                       ("font-size" . "0.6875rem")
                       ("color" . "var(--color-muted)")
                       ("margin-top" . "2px")))
  (".plan-index-bar" (("flex" . "0 0 120px")))

  ;; === CLUSTERS ===
  (".cluster-summary-bar" (("display" . "flex")
                           ("gap" . "8px")
                           ("align-items" . "center")
                           ("font-family" . "var(--font-mono)")
                           ("font-size" . "0.6875rem")
                           ("color" . "var(--color-muted)")
                           ("margin-bottom" . "1.5rem")))
  (".cluster-summary-bar .sep" (("color" . "var(--color-border)")))

  (".cluster-group" (("border" . "1px solid var(--color-border)")
                     ("border-radius" . "2px")
                     ("background" . "var(--color-surface)")
                     ("margin-bottom" . "4px")
                     ("overflow" . "hidden")))
  (".cluster-header" (("display" . "flex")
                      ("align-items" . "center")
                      ("gap" . "10px")
                      ("padding" . "8px 12px")
                      ("cursor" . "pointer")))
  (".cluster-header:hover" (("background" . "var(--color-surface-2)")))
  (".cluster-color-bar" (("width" . "4px")
                         ("height" . "28px")
                         ("border-radius" . "2px")
                         ("flex-shrink" . "0")))
  (".cluster-identity" (("flex" . "1")
                        ("min-width" . "0")
                        ("display" . "flex")
                        ("align-items" . "center")
                        ("gap" . "8px")))
  (".cluster-name" (("font-family" . "var(--font-heading)")
                    ("font-size" . "0.85rem")
                    ("font-weight" . "500")
                    ("color" . "var(--color-heading)")))
  (".cluster-count" (("font-family" . "var(--font-mono)")
                     ("font-size" . "0.6875rem")
                     ("color" . "var(--color-muted)")
                     ("padding" . "1px 6px")
                     ("border" . "1px solid var(--color-border)")
                     ("border-radius" . "2px")))
  (".cluster-metrics" (("display" . "flex")
                       ("align-items" . "center")
                       ("gap" . "8px")
                       ("font-family" . "var(--font-mono)")
                       ("font-size" . "0.6875rem")
                       ("color" . "var(--color-muted)")))
  (".cluster-metric.cross" (("color" . "var(--color-accent)")))
  (".cluster-toggle" (("color" . "var(--color-muted)")
                      ("font-size" . "10px")
                      ("flex-shrink" . "0")))

  (".cluster-body" (("display" . "none")
                    ("padding" . "0 12px 10px 12px")
                    ("border-top" . "1px solid var(--color-border)")))
  (".cluster-body.open" (("display" . "block")))
  (".cluster-summary" (("display" . "flex")
                       ("gap" . "8px")
                       ("font-family" . "var(--font-mono)")
                       ("font-size" . "0.6875rem")
                       ("color" . "var(--color-muted)")
                       ("padding" . "8px 0")
                       ("margin-bottom" . "4px")))
  (".cluster-summary .sep" (("color" . "var(--color-border)")))

  (".cluster-task" (("display" . "flex")
                    ("align-items" . "center")
                    ("gap" . "8px")
                    ("padding" . "3px 0")))
  (".cluster-task-status" (("width" . "8px")
                           ("height" . "8px")
                           ("border-radius" . "50%")
                           ("flex-shrink" . "0")
                           ("background" . "var(--color-muted)")))
  (".cluster-task-status.completed" (("background" . "var(--color-success)")))
  (".cluster-task-status.active" (("background" . "#58a6ff")))
  (".cluster-task-name" (("color" . "var(--color-text)")
                         ("font-size" . "0.78rem")
                         ("text-decoration" . "none")))
  (".cluster-task-name:hover" (("color" . "var(--color-heading)")
                               ("text-decoration" . "underline")))
  (".cluster-task-obs" (("font-family" . "var(--font-mono)")
                        ("font-size" . "0.6875rem")
                        ("color" . "var(--color-muted)")))
  (".cluster-task-date" (("font-family" . "var(--font-mono)")
                         ("font-size" . "0.6875rem")
                         ("color" . "var(--color-muted)")
                         ("margin-left" . "auto")))

  ;; density bar (inline)
  (".density-bar" (("width" . "48px")
                   ("height" . "6px")
                   ("background" . "var(--color-surface-2)")
                   ("border-radius" . "2px")
                   ("overflow" . "hidden")))
  (".density-fill" (("height" . "100%")
                    ("border-radius" . "2px")))

  (".singleton-grid" (("display" . "none")
                      ("flex-wrap" . "wrap")
                      ("gap" . "4px")
                      ("padding-top" . "8px")))
  (".singleton-grid.open" (("display" . "flex")))
  (".singletons-header" (("cursor" . "pointer")
                         ("font-family" . "var(--font-mono)")
                         ("font-size" . "0.7rem")
                         ("font-weight" . "400")
                         ("letter-spacing" . "0.1em")
                         ("text-transform" . "uppercase")
                         ("color" . "var(--color-muted)")
                         ("margin" . "1.5rem 0 0 0")))
  (".singleton-item" (("display" . "inline-flex")
                      ("align-items" . "center")
                      ("gap" . "6px")
                      ("padding" . "4px 10px")
                      ("border" . "1px solid var(--color-border)")
                      ("border-radius" . "2px")
                      ("color" . "var(--color-text)")
                      ("font-size" . "0.75rem")
                      ("text-decoration" . "none")))
  (".singleton-item:hover" (("border-color" . "var(--color-accent-dim)"))))
