;;;; KLI Dashboard — Sessions page CSS

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-sessions
  ;; Section
  (".sessions-section" (("margin-bottom" . "2rem")))
  ;; Active sessions grid
  (".active-sessions-grid" (("display" . "grid")
                            ("grid-template-columns" . "repeat(auto-fill, minmax(320px, 1fr))")
                            ("gap" . "0.75rem")))
  ;; Session card
  (".session-card" (("border" . "1px solid var(--color-border)")
                    ("border-radius" . "2px")
                    ("padding" . "0.75rem 1rem")
                    ("background" . "var(--color-surface)")))
  (".session-card.active-session" (("border-left" . "3px solid var(--color-success)")))
  (".session-header" (("display" . "flex")
                      ("align-items" . "center")
                      ("gap" . "0.5rem")
                      ("margin-bottom" . "0.5rem")))
  (".session-id" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.75rem")
                  ("padding" . "2px 8px")
                  ("border-radius" . "2px")))
  (".session-id.small" (("font-size" . "0.6875rem")
                        ("padding" . "1px 6px")))
  (".session-status" (("font-family" . "var(--font-mono)")
                      ("font-size" . "0.625rem")
                      ("letter-spacing" . "0.1em")
                      ("text-transform" . "uppercase")))
  (".session-status.active" (("color" . "var(--color-success)")))
  (".session-ago" (("margin-left" . "auto")
                   ("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")
                   ("color" . "var(--color-muted)")))
  ;; Meta row
  (".session-meta-row" (("display" . "flex")
                        ("gap" . "1rem")
                        ("margin-bottom" . "0.5rem")))
  (".session-metric" (("font-family" . "var(--font-mono)")
                      ("font-size" . "0.6875rem")
                      ("color" . "var(--color-muted)")))
  ;; Task list
  (".session-tasks" (("display" . "flex")
                     ("flex-direction" . "column")
                     ("gap" . "2px")))
  (".session-task-link" (("font-family" . "var(--font-body)")
                         ("font-size" . "0.75rem")
                         ("color" . "var(--color-accent-dim)")
                         ("text-decoration" . "none")
                         ("padding" . "1px 0")))
  (".session-task-link:hover" (("color" . "var(--color-accent)")))
  (".session-more" (("font-family" . "var(--font-mono)")
                    ("font-size" . "0.6875rem")
                    ("color" . "var(--color-muted)")))
  ;; Depot badges
  (".session-depots" (("display" . "flex")
                      ("gap" . "0.3rem")
                      ("margin-top" . "0.4rem")))
  (".session-depot-badge" (("font-family" . "var(--font-mono)")
                           ("font-size" . "0.625rem")
                           ("padding" . "1px 6px")
                           ("border" . "1px solid var(--color-border)")
                           ("border-radius" . "2px")
                           ("color" . "var(--color-muted)")))
  ;; History table
  (".session-history" (("display" . "flex")
                       ("flex-direction" . "column")
                       ("gap" . "1px")
                       ("background" . "var(--color-border)")
                       ("border" . "1px solid var(--color-border)")
                       ("border-radius" . "2px")
                       ("overflow" . "hidden")))
  (".session-history-header" (("display" . "grid")
                              ("grid-template-columns" . "100px 80px 80px 80px 80px 50px")
                              ("gap" . "0.5rem")
                              ("padding" . "0.5rem 0.75rem")
                              ("background" . "var(--color-surface)")
                              ("font-family" . "var(--font-mono)")
                              ("font-size" . "0.625rem")
                              ("letter-spacing" . "0.1em")
                              ("text-transform" . "uppercase")
                              ("color" . "var(--color-muted)")))
  (".session-row" (("display" . "grid")
                   ("grid-template-columns" . "100px 80px 80px 80px 80px 50px")
                   ("gap" . "0.5rem")
                   ("align-items" . "center")
                   ("padding" . "0.4rem 0.75rem")
                   ("background" . "var(--color-bg)")
                   ("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")))
  (".session-row:hover" (("background" . "var(--color-surface)")))
  (".session-row-tasks" (("color" . "var(--color-text)")))
  (".session-row-events" (("color" . "var(--color-text)")))
  (".session-row-duration" (("color" . "var(--color-muted)")))
  (".session-row-ago" (("color" . "var(--color-muted)")))
  (".session-row-left" (("font-size" . "0.5625rem")
                        ("color" . "var(--color-muted)")
                        ("letter-spacing" . "0.1em")
                        ("text-transform" . "uppercase")))
  ;; Responsive
  ("@media (max-width: 640px)"
    (".active-sessions-grid" (("grid-template-columns" . "1fr")))
    (".session-history-header" (("display" . "none")))
    (".session-row" (("grid-template-columns" . "1fr 1fr 1fr")
                     ("gap" . "0.25rem")))))
