;;;; KLI Dashboard — Stats page CSS

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-stats
  ;; Summary cards
  (".stats-summary" (("display" . "grid")
                     ("grid-template-columns" . "repeat(auto-fit, minmax(120px, 1fr))")
                     ("gap" . "1px")
                     ("background" . "var(--color-border)")
                     ("border" . "1px solid var(--color-border)")
                     ("border-radius" . "2px")
                     ("margin-bottom" . "2rem")
                     ("overflow" . "hidden")))
  (".stats-card" (("background" . "var(--color-surface)")
                  ("padding" . "1.2rem 1rem")
                  ("text-align" . "center")))
  (".stats-number" (("font-family" . "var(--font-heading)")
                    ("font-size" . "1.5rem")
                    ("color" . "var(--color-heading)")
                    ("line-height" . "1")))
  (".stats-label" (("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")
                   ("letter-spacing" . "0.12em")
                   ("text-transform" . "uppercase")
                   ("color" . "var(--color-muted)")
                   ("margin-top" . "0.4rem")))
  ;; Section
  (".stats-section" (("margin-bottom" . "2rem")))
  (".stats-heading" (("font-family" . "var(--font-mono)")
                     ("font-size" . "0.75rem")
                     ("letter-spacing" . "0.1em")
                     ("text-transform" . "uppercase")
                     ("color" . "var(--color-muted)")
                     ("margin-bottom" . "1rem")
                     ("padding-bottom" . "0.5rem")
                     ("border-bottom" . "1px solid var(--color-border)")))
  (".stats-heading .count" (("font-weight" . "normal")
                            ("color" . "var(--color-muted)")))
  ;; Two-column layout
  (".stats-columns" (("display" . "grid")
                     ("grid-template-columns" . "1fr 1fr")
                     ("gap" . "2rem")
                     ("margin-bottom" . "2rem")))
  ;; Status ring + legend
  (".stats-ring-row" (("display" . "flex")
                      ("align-items" . "center")
                      ("gap" . "1.5rem")))
  (".stats-legend" (("display" . "flex")
                    ("flex-direction" . "column")
                    ("gap" . "0.5rem")))
  (".legend-item" (("display" . "flex")
                   ("align-items" . "center")
                   ("gap" . "0.5rem")
                   ("font-family" . "var(--font-body)")
                   ("font-size" . "0.8rem")
                   ("color" . "var(--color-text)")))
  (".legend-dot" (("width" . "10px")
                  ("height" . "10px")
                  ("border-radius" . "2px")
                  ("flex-shrink" . "0")))
  ;; Stats table (horizontal bars)
  (".stats-table" (("display" . "flex")
                   ("flex-direction" . "column")
                   ("gap" . "0.4rem")))
  (".stats-table-row" (("display" . "flex")
                       ("align-items" . "center")
                       ("gap" . "0.75rem")
                       ("padding" . "0.35rem 0.5rem")
                       ("border-radius" . "2px")
                       ("transition" . "background 0.15s")))
  (".stats-table-row:hover" (("background" . "var(--color-surface)")))
  (".stats-table-label" (("font-family" . "var(--font-mono)")
                         ("font-size" . "0.75rem")
                         ("color" . "var(--color-text)")
                         ("min-width" . "140px")
                         ("flex-shrink" . "0")))
  (".stats-task-link" (("color" . "var(--color-accent-dim)")
                       ("text-decoration" . "none")))
  (".stats-task-link:hover" (("color" . "var(--color-accent)")))
  (".stats-bar-track" (("flex" . "1")
                       ("height" . "6px")
                       ("background" . "var(--color-border)")
                       ("border-radius" . "1px")
                       ("overflow" . "hidden")))
  (".stats-bar-fill" (("height" . "100%")
                      ("background" . "var(--color-accent)")
                      ("border-radius" . "1px")
                      ("transition" . "width 0.3s ease")))
  (".stats-table-value" (("font-family" . "var(--font-mono)")
                         ("font-size" . "0.6875rem")
                         ("color" . "var(--color-muted)")
                         ("min-width" . "60px")
                         ("text-align" . "right")
                         ("flex-shrink" . "0")))
  ;; Responsive
  ("@media (max-width: 640px)"
    (".stats-columns" (("grid-template-columns" . "1fr")))))
