;;;; KLI Dashboard — Task Detail CSS
;;;; Header with topic color, metadata, fiber-grouped connections,
;;;; observations, handoffs, action bar.

(in-package :kli-dashboard)

(lol-reactive:defcss :kli-task-detail

  ;; === DETAIL HEADER ===
  (".detail-header" (("padding" . "16px 0 16px 14px")
                     ("margin-bottom" . "1.5rem")
                     ("border-left" . "4px solid var(--color-accent)")))
  (".detail-title" (("font-family" . "var(--font-heading)")
                    ("font-size" . "1.15rem")
                    ("color" . "var(--color-heading)")
                    ("margin" . "0 0 2px 0")))
  (".detail-id" (("font-family" . "var(--font-mono)")
                 ("font-size" . "0.6875rem")
                 ("color" . "var(--color-muted)")
                 ("letter-spacing" . "0.02em")))
  (".detail-meta" (("display" . "flex")
                   ("gap" . "12px")
                   ("flex-wrap" . "wrap")
                   ("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")
                   ("color" . "var(--color-muted)")
                   ("margin-top" . "8px")))
  (".detail-meta-accent" (("color" . "var(--color-accent)")))
  (".detail-meta-link" (("color" . "var(--color-accent-dim)")
                        ("text-decoration" . "none")))
  (".detail-meta-link:hover" (("color" . "var(--color-accent)")
                              ("text-decoration" . "underline")))

  ;; === ACTIONS BAR ===
  (".detail-actions" (("display" . "flex")
                      ("gap" . "8px")
                      ("align-items" . "center")
                      ("margin-bottom" . "1.5rem")
                      ("padding-bottom" . "1rem")
                      ("border-bottom" . "1px solid var(--color-border)")))
  (".detail-action-btn" (("font-family" . "var(--font-mono)")
                         ("font-size" . "0.6875rem")
                         ("letter-spacing" . "0.06em")
                         ("text-transform" . "uppercase")
                         ("padding" . "4px 12px")
                         ("border" . "1px solid var(--color-border)")
                         ("border-radius" . "2px")
                         ("background" . "transparent")
                         ("color" . "var(--color-muted)")
                         ("cursor" . "pointer")
                         ("transition" . "all 0.15s ease")))
  (".detail-action-btn:hover" (("color" . "var(--color-text)")
                               ("border-color" . "var(--color-accent-dim)")))
  (".detail-complete-btn" (("border-color" . "rgba(74,222,128,0.3)")
                           ("color" . "var(--color-success)")))
  (".detail-complete-btn:hover" (("border-color" . "var(--color-success)")
                                 ("background" . "rgba(74,222,128,0.06)")))
  (".detail-status-badge" (("font-family" . "var(--font-mono)")
                           ("font-size" . "0.6875rem")
                           ("padding" . "2px 8px")
                           ("border-radius" . "2px")
                           ("letter-spacing" . "0.06em")
                           ("text-transform" . "uppercase")))
  (".detail-status-badge.completed" (("background" . "rgba(74,222,128,0.12)")
                                     ("color" . "var(--color-success)")))

  ;; === DETAIL SECTIONS ===
  (".detail-section" (("margin-bottom" . "1.5rem")))
  (".detail-section-label" (("font-family" . "var(--font-mono)")
                            ("font-size" . "0.6875rem")
                            ("letter-spacing" . "0.12em")
                            ("text-transform" . "uppercase")
                            ("color" . "var(--color-muted)")
                            ("margin-bottom" . "0.5rem")
                            ("display" . "flex")
                            ("align-items" . "center")
                            ("gap" . "0.5rem")))
  (".detail-section-count" (("color" . "var(--color-accent-dim)")))
  (".detail-desc" (("font-family" . "var(--font-body)")
                   ("font-size" . "0.82rem")
                   ("color" . "var(--color-text)")
                   ("line-height" . "1.5")))
  (".detail-goals" (("margin" . "0")
                    ("padding-left" . "16px")
                    ("font-size" . "0.82rem")
                    ("color" . "var(--color-text)")
                    ("line-height" . "1.6")))
  (".detail-goals li" (("margin-bottom" . "2px")))

  ;; === METADATA ROW ===
  (".detail-metadata-row" (("display" . "flex")
                           ("flex-wrap" . "wrap")
                           ("gap" . "16px")
                           ("font-size" . "0.78rem")))
  (".detail-metadata-row .meta-key" (("color" . "var(--color-muted)")))
  (".detail-metadata-row .meta-val" (("color" . "var(--color-accent)")
                                     ("font-weight" . "500")))
  (".detail-tag" (("font-family" . "var(--font-mono)")
                  ("font-size" . "0.6875rem")
                  ("letter-spacing" . "0.06em")
                  ("text-transform" . "uppercase")
                  ("padding" . "2px 8px")
                  ("border-radius" . "2px")
                  ("background" . "var(--color-surface-2)")
                  ("border" . "1px solid var(--color-border)")
                  ("color" . "var(--color-muted)")
                  ("margin-right" . "4px")))

  ;; === FIBER-GROUPED CONNECTIONS ===
  (".connection-fiber" (("margin-bottom" . "12px")))
  (".fiber-label" (("font-family" . "var(--font-mono)")
                   ("font-size" . "0.6875rem")
                   ("font-weight" . "600")
                   ("letter-spacing" . "0.06em")
                   ("text-transform" . "uppercase")
                   ("padding" . "2px 0")
                   ("margin-bottom" . "4px")))
  (".fiber-structural" (("color" . "#a371f7")))
  (".fiber-causal" (("color" . "#f85149")))
  (".fiber-declared" (("color" . "#d29922")))
  (".fiber-inferred" (("color" . "var(--color-muted)")))
  (".connections-list" (("list-style" . "none")
                        ("padding" . "0")
                        ("margin" . "0")))
  (".connection-item" (("display" . "flex")
                       ("align-items" . "center")
                       ("gap" . "8px")
                       ("padding" . "4px 0")
                       ("border-bottom" . "1px solid var(--color-border)")))
  (".connection-item:last-child" (("border-bottom" . "none")))
  (".connection-layer" (("font-family" . "var(--font-mono)")
                        ("font-size" . "0.6875rem")
                        ("padding" . "1px 6px")
                        ("border-radius" . "2px")
                        ("text-transform" . "uppercase")
                        ("letter-spacing" . "0.04em")
                        ("white-space" . "nowrap")
                        ("flex-shrink" . "0")))
  (".connection-layer.phase-of, .connection-layer.spawned"
   (("background" . "rgba(163,113,247,0.12)") ("color" . "#a371f7")))
  (".connection-layer.depends-on, .connection-layer.enables, .connection-layer.blocks"
   (("background" . "rgba(248,81,73,0.12)") ("color" . "#f85149")))
  (".connection-layer.related-to"
   (("background" . "rgba(210,153,34,0.12)") ("color" . "#d29922")))
  (".connection-layer.topic, .connection-layer.reference, .connection-layer.same-day"
   (("background" . "var(--color-surface-2)") ("color" . "var(--color-muted)")))
  (".connection-name" (("color" . "var(--color-text)")
                       ("text-decoration" . "none")
                       ("font-size" . "0.78rem")))
  (".connection-name:hover" (("color" . "var(--color-heading)")
                             ("text-decoration" . "underline")))
  (".connection-dir" (("font-family" . "var(--font-mono)")
                      ("font-size" . "0.6875rem")
                      ("color" . "var(--color-muted)")
                      ("flex-shrink" . "0")))

  ;; === OBSERVATIONS ===
  (".obs-item" (("padding" . "6px 0 6px 8px")
                ("border-left" . "2px solid var(--color-border)")
                ("margin-bottom" . "6px")))
  (".obs-time" (("font-family" . "var(--font-mono)")
                ("font-size" . "0.6875rem")
                ("color" . "var(--color-muted)")
                ("display" . "block")
                ("margin-bottom" . "1px")))
  (".obs-text" (("font-family" . "var(--font-body)")
                ("font-size" . "0.75rem")
                ("color" . "var(--color-text)")
                ("line-height" . "1.5")))

  ;; === HANDOFFS ===
  (".handoff-item" (("border-bottom" . "1px solid var(--color-border)")))
  (".handoff-summary" (("padding" . "6px 0")
                       ("cursor" . "pointer")
                       ("color" . "var(--color-accent)")
                       ("font-family" . "var(--font-mono)")
                       ("font-size" . "0.75rem")
                       ("user-select" . "none")))
  (".handoff-summary:hover" (("color" . "var(--color-heading)")))
  (".handoff-content" (("white-space" . "pre-wrap")
                       ("font-size" . "0.72rem")
                       ("line-height" . "1.5")
                       ("color" . "var(--color-text)")
                       ("max-height" . "300px")
                       ("overflow-y" . "auto")
                       ("padding" . "8px 10px")
                       ("margin" . "0 0 6px 0")
                       ("background" . "var(--color-surface)")
                       ("border-radius" . "2px")))

  ;; === SESSIONS ===
  (".session-list" (("display" . "flex")
                    ("flex-wrap" . "wrap")
                    ("gap" . "4px")))
  (".session-badge" (("font-family" . "var(--font-mono)")
                     ("font-size" . "0.6875rem")
                     ("padding" . "1px 6px")
                     ("border-radius" . "2px"))))
