(in-package #:kli/tui/views)

(defextension tui-views
  (:provides
   (method cursor-position () (tui-view t) (view width)
     (declare (ignore width))
     nil)
   (method handle-input () (tui-view t) (view input)
     (declare (ignore input))
     nil)
   (method handle-paste () (tui-view t) (view text)
     (declare (ignore text))
     nil)
   (method set-focused () (tui-view t) (view state)
     (declare (ignore state))
     nil)
   (method invalidate () (tui-view) (view)
     (declare (ignore view))
     nil)
   (method children () (tui-view) (view)
     (declare (ignore view))
     '())
   (method render-lines () (tui-text-view t) (view width)
     (render-text-lines view width))
   (method render-lines () (tui-container-view t) (view width)
     (render-container-lines view width))
   (method invalidate () (tui-container-view) (view)
     (invalidate-container view))
   (method children () (tui-container-view) (view)
     (container-children view))
   (method add-child () (tui-container-view t) (view child)
     (container-add-child view child))
   (method remove-child () (tui-container-view t) (view child)
     (container-remove-child view child))
   (method clear-children () (tui-container-view) (view)
     (container-clear-children view))
   (method render-lines () (tui-box-view t) (view width)
     (render-box-lines view width))))
