(defpackage #:kli/tui/app
  (:use #:cl)
  (:import-from #:kli
                #:next-keyword-id
                #:make-id-counter
                #:active-protocol
                #:find-live-object
                #:live-object
                #:context-registry
                #:object-id
                #:object-protocol
                #:register-live-object)
  (:import-from #:kli/ext
                #:defextension
                #:make-provider
                #:make-provider-contract
                #:protocol-storage
                #:boot-marker
                #:with-boot-stage)
  (:import-from #:kli/tui/style
                #:set-active-theme
                #:detect-color-mode
                #:*color-mode*
                #:+theme-mode-key+)
  (:import-from #:kli/tui/commands
                #:dispatch-slash-command)
  (:import-from #:kli/agent/session
                #:abort-agent-session
                #:agent-session-busy-p
                #:current-agent-session-leaf-id
                #:drain-agent-session-work
                #:make-session-event-listener
                #:queue-agent-session-steer
                #:register-session-event-listener
                #:resume-agent-session
                #:retract-agent-session-pending-prompt
                #:rewind-agent-session
                #:rewind-agent-session-available-p
                #:list-rewind-targets
                #:session-mode-bindings
                #:session-mode-info
                #:submit-agent-session-prompt
                #:unregister-session-event-listener)
   (:import-from #:kli/agent/loop
                 #:*defer-agent-turn-p*)
  (:import-from #:kli/tui/input
                #:make-input-route-context
                #:make-input-decoder
                #:route-input-event
                #:input-event-kind
                #:input-decoder-buffer
                #:input-decoder-flush
                #:input-decoder-feed)
  (:import-from #:kli/tui/editor
                #:editor-value
                #:set-editor-value
                #:open-editor-selection
                #:make-completion-candidate
                #:completion-candidate-value)
  (:import-from #:kli/tui/transcript
                #:make-transcript
                #:make-transcript-view
                #:make-scrollback-renderer
                #:transcript-view-editor
                #:transcript-events
                #:transcript-add-event
                #:transcript-remove-last-user-event
                #:make-transcript-event
                #:event-status
                #:scrollback-clear-screen
                #:scrollback-anchor-bottom
                #:scrollback-renderer-notice
                #:scrollback-renderer-streaming-event
                #:transcript-clear
                #:scrollback-reset
                #:begin-scrollback-stream
                #:finalize-scrollback-stream
                #:toggle-tool-output-expansion)
  (:import-from #:kli/tui/terminal
                #:make-memory-terminal
                #:make-process-terminal
                #:process-terminal
                #:terminal-columns
                #:terminal-rows
                #:terminal-clear-screen
                #:terminal-begin-frame
                #:terminal-end-frame
                #:terminal-enable-bracketed-paste
                #:terminal-disable-bracketed-paste
                #:process-terminal-size
                #:call-with-terminal-character-input
                #:call-with-raw-terminal
                #:terminal-input-tty-p
                #:write-terminal-control
                #:query-terminal-background
                #:resolve-background-mode
                #:parse-colorfgbg)
  (:import-from #:kli/tui/core
                #:make-behavior-cell
                #:call-behavior
                #:set-focused
                #:render-frame
                #:recode-tui-behavior)
  (:export
   #:tui-app
   #:make-tui-app
   #:register-tui-app
   #:reattach-tui-app
   #:unregister-tui-app-listener
   #:tui-app-terminal
   #:tui-app-decoder
   #:tui-app-transcript
   #:tui-app-view
   #:tui-app-renderer
   #:tui-app-context
   #:tui-app-route-context
   #:tui-app-runtime-behavior
   #:tui-app-running-p
   #:tui-app-interrupt-armed-p
   #:tui-app-abort-armed-at
   #:tui-app-rewind-armed-at
   #:tui-app-notice-expires-at
   #:tui-app-pending-prompt
   #:tui-app-pre-turn-leaf-id
   #:tui-app-retract-armed-p
   #:tui-app-on-submit
   #:tui-app-mode-id
   #:tui-app-listener-id
   #:tui-app-active-session-id
   #:tui-app-projection-buffer
   #:tui-app-agent-worker-thread
   #:tui-app-command-worker-thread
   #:tui-app-spinner-active-p
   #:tui-app-spinner-phase
   #:tui-app-tool-update-text
   #:tui-app-editor
   #:tui-app-editor-value
   #:tui-app-transcript-events

   #:tui-app-add-event
   #:tui-app-add-system-event
   #:clear-tui-app-screen
   #:reset-tui-app
   #:request-tui-app-interrupt
   #:request-tui-app-abort
   #:open-tui-app-rewind-menu
   #:open-tui-app-branches-menu
   #:open-tui-app-resume-menu
   #:open-tui-app-menu
   #:stop-tui-app
   #:render-tui-app
   #:redraw-tui-app
   #:route-tui-app-event
   #:route-tui-app-events
   #:flush-tui-app-input
   #:tui-app-feed
   #:tui-app-step
   #:tui-app-runtime-step
   #:recode-tui-app-runtime
   #:enqueue-main-thread-task
   #:call-on-main-thread-task
   #:run-tui-app
   #:resolve-auto-theme-mode
   #:*tui-app-extension-manifest*
   #:apply-tui-app-event-projection
   #:default-tui-app-on-submit
   #:run-pending-main-thread-tasks
   #:tui-app-render-fault-streak
   #:tui-app-render-reset-pending-p
   #:poll-tui-app-spinner

   #:tui-surface
   #:make-tui-surface
   #:surface-id
   #:surface-label
   #:surface-view
   #:surface-renderer
   #:surface-route-context
   #:tui-app-surfaces
   #:tui-app-active-surface-index
   #:tui-app-active-surface
   #:tui-app-route-interceptors
   #:add-tui-app-surface
   #:remove-tui-app-surface
   #:list-tui-app-surfaces
   #:active-tui-app-surface
   #:select-tui-app-surface
   #:cycle-tui-app-surface
   #:add-tui-app-route-interceptor
   #:remove-tui-app-route-interceptor
   #:run-tui-app-route-interceptors
   #:request-tui-app-render))

(in-package #:kli/tui/app)
