(defpackage #:kli/agent/loop
  (:use #:cl)
  (:import-from #:kli
                #:next-keyword-id
                #:make-id-counter
                #:active-protocol
                #:context-registry
                #:find-live-object
                #:live-object
                #:object-id
                #:register-live-object
                #:remove-live-object)
  (:import-from #:kli/ext
                #:defextension
                #:find-capability-provider
                #:invoke-tool
                #:make-provider
                #:make-provider-contract
                #:make-subject
                #:make-default-subject
                #:subject-grant
                #:make-grant-contribution
                #:install-contribution
                #:principal-subject
                #:grant-set-has-p
                #:make-tool-result
                #:make-tool-text-content
                #:provider-call
                #:require-capability-provider
                #:*call-subject*
                #:tool-error-result
                #:tool-result-content
                #:tool-result-details
                #:tool-result-error-p)
  (:import-from #:kli/model/runtime
                #:assistant-delta
                #:assistant-delta-text
                #:thinking-delta
                #:thinking-delta-text
                #:usage-delta
                #:usage-delta-usage
                #:model-request-provider
                #:model-response-content
                #:model-response-metadata
                #:model-response-stop-reason
                #:model-response-tool-calls
                #:parse-tool-call-arguments)
  (:import-from #:kli/session/log
                #:agent-message-p
                #:message-content
                #:session-uuid)
  (:export
   #:agent-loop-service
   #:agent
   #:agent-state
   #:agent-turn
   #:agent-queue
   #:agent-loop-run
   #:tool-call
   #:tool-execution
   #:tool-execution-update

   #:make-agent-loop-service
   #:make-agent
   #:make-agent-loop-behavior
   #:make-tool-call
   #:register-agent
   #:deregister-agent
   #:agent-loop-service-agents
   #:agent-session
   #:agent-store
   #:agent-context
   #:agent-model-selection
   #:agent-model-runtime
   #:agent-system-prompt
   #:agent-base-system-prompt
   #:agent-context-extras-fn
   #:agent-state
   #:agent-state-value
   #:agent-state-reason
   #:set-agent-state
   #:agent-current-turn
   #:agent-turns
   #:agent-tool-executions
   #:agent-steering-queue
   #:agent-follow-up-queue
   #:agent-abort-requested-p
   #:agent-last-error
   #:*agent-error-supervised-p*
    #:*defer-agent-turn-p*
   #:agent-behavior
   #:agent-subject
   #:agent-principal
   #:agent-loop-runs
   #:seed-agent-principal-grant
   #:agent-queue-items
   #:agent-turn-state
   #:agent-turn-request
   #:agent-turn-response
   #:agent-turn-tool-calls
   #:agent-tool-call-id
   #:agent-tool-call-name
   #:agent-tool-call-arguments
   #:agent-tool-call-state
   #:tool-execution-call
   #:tool-execution-result
   #:tool-execution-state
   #:tool-execution-updates

   #:prompt-agent
   #:continue-agent
   #:steer-agent
   #:queue-agent-steer
   #:follow-up-agent
   #:abort-agent
   #:run-agent-loop
   #:run-one-agent-turn
   #:execute-agent-tool-call
   #:agent-idle-p
   #:agent-active-p
   #:drain-pending-agent-work
   #:inspect-agent
   #:inspect-agent-turn
   #:inspect-tool-execution
   #:agent-behavior-value
   #:recode-agent-loop-behavior
   #:*agent-loop-extension-manifest*))

(in-package #:kli/agent/loop)
