(defpackage #:kli/profiles
  (:use #:cl)
  (:import-from #:kli/ext
                #:contribution
                #:contribution-name
                #:defcontribution-kind
                #:defextension
                #:ensure-protocol-storage
                #:extension-protocol
                #:install-contribution
                #:install-manifest-list
                #:normalize-extension-id
                #:protocol-installed-contributions
                #:protocol-storage
                #:retract-contribution
                #:retract-installed-extensions)
  (:export
   #:profile-contribution
   #:make-profile-contribution
   #:contribution-manifest-group
   #:contribution-seam
   #:profile-activation
   #:make-profile-activation
   #:profile-activation-id
   #:profile-activation-extensions
   #:profile-activation-seam
   #:protocol-profile-activations
   #:protocol-profile-activation
   #:unknown-profile
   #:unknown-profile-name
   #:unknown-profile-known
   #:find-profile-manifest
   #:known-profile-names
   #:record-active-profile
   #:protocol-active-profile
   #:*default-profile-base*
   #:profile-spec
   #:make-profile-spec
   #:profile-spec-p
   #:profile-spec-name
   #:profile-spec-extends
   #:profile-spec-enable
   #:profile-spec-disable
   #:profile-spec-settings
   #:parse-profile-specs
   #:resolved-profile
   #:make-resolved-profile
   #:resolved-profile-p
   #:resolved-profile-name
   #:resolved-profile-base
   #:resolved-profile-enable
   #:resolved-profile-disable
   #:resolved-profile-settings
   #:resolve-profile-spec
   #:*baseline-extension-manifests*
   #:*model-provider-extension-manifests*
   #:*tui-app-extension-manifests*
   #:*nix-declared-extension-manifests*
   #:*nix-declared-baseline-ids*
   #:*headless-extension-manifest*
   #:*print-extension-manifest*
   #:*interactive-terminal-extension-manifest*
   #:*human-in-loop-extension-manifest*
   #:*autonomous-extension-manifest*))

(in-package #:kli/profiles)
