(in-package #:kli/tui/transcript)

(defextension tui-transcript
  (:provides
   (event-type :tui-error)
   (event-type :tui/user-submitted)
   (method handle-input () (transcript-view t) (view input)
     (handle-transcript-input view input))
   (method handle-paste () (transcript-view t) (view text)
     (handle-transcript-paste view text))
   (method invalidate () (transcript-view) (view)
     (invalidate-transcript-view view))
   (method dismiss-overlay () (transcript-view) (view)
     (dismiss-overlay (transcript-view-editor view)))
   (method set-focused () (transcript-view t) (view state)
     (set-transcript-focused view state))
   (method render-frame () (scrollback-renderer t) (renderer terminal &key force)
     (render-scrollback-frame renderer terminal :force force))
   (method recode-tui-behavior () (scrollback-renderer) (renderer &rest args)
     (apply #'recode-scrollback renderer args))
   (method project-event-to-transcript () ((eql :tui/user-submitted) t t t)
     (event-type event mode-id buffer)
     (project-user-submitted event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/delta) t t t)
     (event-type event mode-id buffer)
     (project-assistant-delta event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/thinking-delta) t t t)
     (event-type event mode-id buffer)
     (project-agent-thinking-delta event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/message-end) t t t)
     (event-type event mode-id buffer)
     (project-assistant-message-end event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/tool-execution-start) t t t)
     (event-type event mode-id buffer)
     (project-tool-execution-start event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/tool-execution-end) t t t)
     (event-type event mode-id buffer)
     (project-tool-execution-end event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :session-switch) t t t)
     (event-type event mode-id buffer)
     (project-session-switch event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :session-branch) t t t)
     (event-type event mode-id buffer)
     (project-session-branch event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :session-reset) t t t)
     (event-type event mode-id buffer)
     (project-session-reset event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :model-change) t t t)
     (event-type event mode-id buffer)
     (project-model-change event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :option-change) t t t)
     (event-type event mode-id buffer)
     (project-option-change event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/retry) t t t)
     (event-type event mode-id buffer)
     (project-agent-retry event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :agent/error) t t t)
     (event-type event mode-id buffer)
     (project-agent-error event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :session-compaction-started) t t t)
     (event-type event mode-id buffer)
     (project-compaction-started event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :session-compaction-finished) t t t)
     (event-type event mode-id buffer)
     (project-compaction-finished event-type event mode-id buffer))
   (method project-event-to-transcript () ((eql :tui-error) t t t)
     (event-type event mode-id buffer)
     (project-tui-error event-type event mode-id buffer))
   (method render-transcript-event () (t t t t t) (kind protocol event theme width)
     (render-transcript-event-default kind protocol event theme width))))
