(defpackage #:kli/model/runtime
  (:use #:cl)
  (:import-from #:kli
                #:next-keyword-id
                #:make-id-counter
                #:next-counter-value
                #:active-protocol
                #:context-registry
                #:find-live-object
                #:live-object
                #:object-id
                #:register-live-object
                #:remove-live-object)
  (:import-from #:kli/ext
                #:defextension
                #:make-provider
                #:make-provider-contract
                #:provider-call
                #:require-capability-provider)
  (:import-from #:kli/auth/core
                #:resolved-credential-reference-id
                #:resolved-credential-source-kind)
  (:import-from #:kli/context/lens
                #:context-model-messages
                #:sealed-context-epoch
                #:sealed-context-source-context-id
                #:sealed-context-leaf-id)
  (:import-from #:kli/model/registry
                #:model-selection-provider-id
                #:model-selection-model-id
                #:model-provider-auth-required-p
                #:model-provider-credential-provider-id
                #:model-provider-api)
  (:import-from #:kli/session/log
                #:message-role
                #:message-content
                #:message-metadata
                #:tool-call-id
                #:tool-name
                #:tool-error-p)
  (:export
   #:model-runtime
   #:model-request
   #:model-response
   #:model-stream
   #:model-delta
   #:assistant-delta
   #:thinking-delta
   #:tool-call-delta
   #:usage-delta
   #:block-boundary-delta
   #:block-start-delta
   #:block-end-delta
   #:stop-reason-delta
   #:stop-reason-delta-reason

   #:make-model-runtime
   #:make-assistant-delta
   #:make-thinking-delta
   #:make-tool-call-delta
   #:make-usage-delta
   #:make-stop-reason-delta
   #:make-block-start-delta
   #:make-block-end-delta
   #:runtime-requests
   #:runtime-streams
   #:runtime-responses
   #:runtime-stream-adapters
   #:model-request-selection
   #:model-request-provider
   #:model-request-sealed-context
   #:model-request-state
   #:model-request-model-messages
   #:model-request-instructions
   #:model-request-session-id
   #:model-request-tool-schemas
   #:model-request-sealed-epoch
   #:model-request-sealed-context-id
   #:model-request-source-context-id
   #:model-request-leaf-id
   #:model-request-provider-id
   #:model-request-model-id
   #:model-request-credential-reference-id
   #:model-request-credential-source-kind
   #:model-request-stream
   #:model-request-stream-closer
   #:model-request-response
   #:model-request-error
   #:model-response-content
   #:model-response-tool-calls
   #:model-response-stop-reason
   #:model-response-request-id
   #:model-response-metadata
   #:model-stream-request
   #:model-stream-events
   #:model-stream-state
   #:model-stream-usage
   #:model-stream-provider-stop-reason
   #:model-stream-thinking-deltas
   #:model-delta-kind
   #:model-delta-content-index
   #:model-delta-timestamp
   #:assistant-delta-text
   #:thinking-delta-text
   #:thinking-delta-signature
   #:thinking-delta-redacted
   #:tool-call-delta-call-id
   #:tool-call-delta-name
   #:tool-call-delta-arguments
   #:usage-delta-usage
   #:block-delta-content-kind

   #:make-model-request
   #:complete-text
   #:parse-tool-call-arguments
   #:stream-model-response
   #:stream-thinking-blocks
   #:register-model-stream-adapter
   #:unregister-model-stream-adapter
   #:find-model-stream-adapter
   #:handle-model-delta
   #:abort-model-request
   #:inspect-model-request
   #:inspect-model-response
   #:inspect-model-stream
   #:*model-runtime-extension-manifest*
   #:make-model-stream))

(in-package #:kli/model/runtime)
