(defpackage #:kli/runtime/snapshot
  (:use #:cl)
  (:import-from #:kli
                #:active-protocol
                #:context-registry
                #:find-live-object
                #:register-live-object
                #:remove-live-object
                #:live-object
                #:object-id)
  (:import-from #:kli/ext
                #:defextension
                #:make-provider
                #:make-provider-contract
                #:require-capability
                #:normalize-extension-id
                #:extension-protocol
                #:make-extension-protocol
                #:protocol-extensions
                #:protocol-installed-contributions
                #:protocol-storage
                #:protocol-storage-table
                #:snapshot-exempt-storage-key-p
                #:protocol-root-activations
                #:extension
                #:extension-source
                #:extension-loaded-p
                #:install-manifest
                #:retract-installed-extensions
                #:live-object-contribution
                #:contribution-object
                #:tool-contribution
                #:contribution-tool
                #:capability-contribution
                #:contribution-provider
                #:provider-contract-contribution
                #:contribution-contract)
  (:export
   #:snapshot-context
   #:restore-active-protocol
   #:snapshot-representation
   #:restore-representation
   #:snapshot-unserializable
   #:serialize-snapshot-value
   #:deserialize-snapshot-value
   #:*replay-remote-installs*
   #:*snapshot-nix-baseline-ids*
   #:*reconcile-baseline-gap*
   #:*snapshot-isolated-ids*
   #:*reconcile-isolated-gap*
   #:*snapshot-extension-manifest*))
