(defpackage #:kli/interaction/commands
  (:use #:cl)
  (:import-from #:kli
                #:active-protocol
                #:live-object
                #:object-id)
  (:import-from #:kli/ext
                #:*call-subject*
                #:capabilities-subject
                #:contribution
                #:contribution-extension
                #:defcontribution-kind
                #:defextension
                #:extension-protocol
                #:find-capability-provider
                #:install-contribution
                #:make-provider
                #:make-provider-contract
                #:make-subject
                #:make-unrestricted-subject
                #:normalize-extension-id
                #:protocol-installed-contributions
                #:provider-call
                #:register-author-clause-requirements
                #:require-capability-provider
                #:retract-contribution
                #:subject-meet)
  (:import-from #:kli/text
                #:split-on-whitespace)
  (:export
   #:command-service
   #:make-command-service
   #:command
   #:make-command
   #:command-name
   #:command-label
   #:command-description
   #:command-arguments
   #:command-runner
   #:command-completer
   #:*command-completion-mode*
   #:command-renderer
   #:command-metadata
   #:command-result
   #:make-command-result
   #:make-command-text-content
   #:command-result-content
   #:command-result-details
   #:command-result-error-p
   #:clone-command
   #:command-registration
   #:registration-command
   #:registration-source
   #:registration-override
   #:registration-priority
   #:registration-qualified-name
   #:register-command
   #:unregister-command
   #:find-command
   #:resolve-command
   #:command-collisions
   #:format-command-collisions
   #:split-qualified-name
   #:tier-priority
   #:list-commands
   #:invoke-command
   #:recode-command
   #:command-signature
   #:command-usage-text
   #:with-operator-capability
   #:call-with-operator-capability
   #:argument-words
   #:make-commands-provider
   #:make-commands-contract
   #:*commands-extension-manifest*

   #:command-contribution
   #:make-command-contribution
   #:contribution-command-name
   #:contribution-command-label
   #:contribution-command-description
   #:contribution-command-arguments
   #:contribution-command-runner
   #:contribution-command-handle
   #:reply
   #:rest-arg))
