(defpackage #:kli/model/registry
  (:use #:cl)
  (:import-from #:kli
                #:next-keyword-id
                #:make-id-counter
                #:active-protocol
                #:context-registry
                #:find-live-object
                #:live-object
                #:object-id
                #:register-live-object
                #:remove-live-object)
  (:import-from #:kli/ext
                #:defextension
                #:make-provider
                #:make-provider-contract
                #:provider-call
                #:require-capability-provider)
  (:export
   #:model-registry
   #:model-provider
   #:model-definition
   #:model-selection
   #:provider-config
    #:model-option-definition
    #:model-option-schema

   #:make-model-registry
   #:make-model-provider
   #:make-model-definition
   #:make-model-selection
   #:make-provider-config
    #:make-model-option-schema
    #:find-model-option-definition
    #:registered-model-option-definitions
    #:normalize-option-id
    #:model-option-definition-id
    #:model-option-definition-type
    #:model-option-definition-label
    #:model-option-definition-enum-values
    #:model-option-schema-option-id
    #:model-option-schema-type
    #:model-option-schema-values
    #:model-option-schema-default
    #:model-option-schema-default-supplied-p
    #:model-option-schema-min
    #:model-option-schema-max
    #:model-definition-option-schemas
    #:model-option-schema-for
    #:model-option-keyword
    #:validate-model-option-schema
    #:canonicalize-model-option-value
    #:parse-model-option-value
    #:materialize-model-options
    #:preserve-valid-model-options
    #:model-supports-option-p
   #:registry-providers
   #:registry-models
   #:registry-current-selection
   #:model-provider-provider-id
   #:model-provider-api
   #:model-provider-auth-required-p
   #:model-provider-credential-provider-id
   #:model-provider-config
   #:model-provider-metadata
   #:model-definition-provider-id
   #:model-definition-model-id
   #:model-definition-api
   #:model-definition-name
   #:model-definition-context-window
   #:model-definition-metadata
   #:model-selection-provider-id
   #:model-selection-model-id
   #:model-selection-options
   #:model-selection-option-value
   #:model-selection-timestamp
   #:model-selection-metadata
   #:provider-config-base-url
   #:provider-config-headers

   #:register-model-provider
   #:register-model-definition
   #:unregister-model-provider
   #:unregister-model-definition
   #:find-model-provider
   #:find-model-definition
   #:selection-context-window
   #:available-models
   #:select-model
   #:current-model-selection
   #:inspect-model-provider
   #:inspect-model-definition
   #:inspect-model-selection
   #:inspect-model-registry
   #:*model-registry-extension-manifest*))

(in-package #:kli/model/registry)
